version: '3.3'
services:
  db:
    image: mysql:8.0
    volumes:
      - /var/lib/mysql/
    restart: always
    environment:
      CHAT_DATABASE_PASSWORD: 
      MYSQL_ROOT_PASSWORD: 
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db