version: '2.1'
services:
  chat_db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql_data:/var/lib/mysql/
    restart: always
    environment:
      MYSQL_DATABASE: chat_development
      MYSQL_USER: chat_user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_HOST: localhost
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  chat_api:
    build: .
    command: sh -c "bin/rails db:migrate && rm tmp/pids/server.pid && bin/rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/myapp
    environment:
      CHAT_DATABASE_PASSWORD: password
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      chat_db:
        condition: service_healthy
volumes:
  mysql_data: